import base64
import json
import logging
import os
import secrets
import re
import string
import subprocess
import time
from flask import Flask, jsonify, request, Response


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("router")

app = Flask(__name__)


def env_int(name, default):
    value = os.getenv(name, str(default))
    try:
        return int(value)
    except ValueError:
        return default


def parse_port_range(value):
    match = re.match(r"^(\d+)-(\d+)$", value or "")
    if not match:
        return (3000, 9999)
    start = int(match.group(1))
    end = int(match.group(2))
    if start > end:
        start, end = end, start
    return (start, end)


def parse_exclude_ports(value):
    ports = set()
    for item in (value or "").split(","):
        item = item.strip()
        if not item:
            continue
        try:
            ports.add(int(item))
        except ValueError:
            continue
    return ports


TARGET_CONTAINER = os.getenv("TARGET_CONTAINER", "opencode-backend")
ROUTES_FILE = "/etc/caddy/routes.conf"
PREVIEW_FILE = "/etc/caddy/preview.conf"
ROUTER_STATE_FILE = os.getenv("ROUTER_STATE_FILE", "/data/routes.json")
SCAN_INTERVAL = env_int("ROUTER_SCAN_INTERVAL", 5)
TOKEN_LENGTH = env_int("ROUTER_TOKEN_LENGTH", 12)
PORT_RANGE = parse_port_range(os.getenv("ROUTER_PORT_RANGE", "3000-9999"))
EXCLUDE_PORTS = parse_exclude_ports(os.getenv("ROUTER_EXCLUDE_PORTS", "4096"))
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").rstrip("/")
PREVIEW_DOMAIN = os.getenv("PREVIEW_DOMAIN", "").strip()
ROUTER_USERNAME = os.getenv("ROUTER_USERNAME", "")
ROUTER_PASSWORD = os.getenv("ROUTER_PASSWORD", "")


def load_state():
    if not os.path.exists(ROUTER_STATE_FILE):
        return {}
    try:
        with open(ROUTER_STATE_FILE, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, json.JSONDecodeError):
        return {}


def save_state(state):
    os.makedirs(os.path.dirname(ROUTER_STATE_FILE), exist_ok=True)
    with open(ROUTER_STATE_FILE, "w", encoding="utf-8") as handle:
        json.dump(state, handle, ensure_ascii=True, indent=2, sort_keys=True)


def generate_token(length):
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def run_cmd(args):
    result = subprocess.run(
        args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
    )
    if result.returncode != 0:
        log.warning(
            "Command failed (rc=%d): %s | stderr: %s",
            result.returncode,
            " ".join(args),
            result.stderr.strip(),
        )
        return None
    return result.stdout


def parse_proc_net_tcp(output):
    ports = set()
    for line in output.splitlines():
        line = line.strip()
        if not line or line.startswith("sl"):
            continue
        parts = line.split()
        if len(parts) < 4:
            continue
        local = parts[1]
        state = parts[3]
        if state != "0A":
            continue
        if ":" not in local:
            continue
        port_hex = local.rsplit(":", 1)[-1]
        try:
            port = int(port_hex, 16)
        except ValueError:
            continue
        ports.add(port)
    return ports


def list_listening_ports():
    output = run_cmd(
        [
            "docker",
            "exec",
            TARGET_CONTAINER,
            "sh",
            "-c",
            "cat /proc/net/tcp /proc/net/tcp6",
        ]
    )
    if output is None:
        log.warning("Failed to query ports from %s", TARGET_CONTAINER)
        return None
    ports = parse_proc_net_tcp(output)
    filtered = []
    start, end = PORT_RANGE
    for port in ports:
        if port in EXCLUDE_PORTS:
            continue
        if port < start or port > end:
            continue
        filtered.append(port)
    log.debug("Discovered ports: %s", filtered)
    return sorted(filtered)


def write_map(state):
    lines = ["# Dynamic routes (auto generated by router)"]
    for token, info in sorted(state.items()):
        if token.startswith("__"):
            continue
        port = info.get("port")
        if not port:
            continue
        lines.append(f"@route_{token} path /p/{token} /p/{token}/*")
        lines.append(f"handle @route_{token} {{")
        lines.append(f"\turi strip_prefix /p/{token}")
        lines.append(f"\treverse_proxy {TARGET_CONTAINER}:{port}")
        lines.append("}")
        lines.append("")
    content = "\n".join(lines) + "\n"
    with open(ROUTES_FILE, "w", encoding="utf-8") as handle:
        handle.write(content)


def reload_gateway():
    run_cmd(["caddy", "reload", "--config", "/etc/caddy/Caddyfile"])


# ---- Preview port management ----

preview_port = None  # Currently active preview port


def load_preview_state():
    global preview_port
    state = load_state()
    preview_port = state.get("__preview_port__")
    if preview_port is not None:
        write_preview_conf(preview_port)
        log.info("Restored preview port: %s", preview_port)


def save_preview_port(port):
    global preview_port
    preview_port = port
    state = load_state()
    if port is None:
        state.pop("__preview_port__", None)
    else:
        state["__preview_port__"] = port
    save_state(state)


def write_preview_conf(port):
    if port:
        content = (
            "# Preview proxy (auto generated by router)\n"
            f"reverse_proxy {TARGET_CONTAINER}:{port}\n"
        )
    else:
        content = (
            "# Preview proxy (no port selected)\n"
            'respond "No preview port configured. '
            'Set one from the Routes panel." 503\n'
        )
    with open(PREVIEW_FILE, "w", encoding="utf-8") as handle:
        handle.write(content)


def set_preview_port(port):
    write_preview_conf(port)
    save_preview_port(port)
    reload_gateway()
    log.info("Preview port set to: %s", port)


def sync_routes():
    state = load_state()
    ports = list_listening_ports()

    if ports is None:
        # docker exec failed — skip this cycle, do NOT clear existing routes
        return

    # Filter out non-route keys (e.g. __preview_port__)
    route_state = {k: v for k, v in state.items() if not k.startswith("__")}
    existing_ports = {info.get("port") for info in route_state.values()}

    changed = False
    for port in ports:
        if port in existing_ports:
            continue
        token = generate_token(TOKEN_LENGTH)
        while token in state:
            token = generate_token(TOKEN_LENGTH)
        state[token] = {
            "port": port,
            "created_at": int(time.time()),
        }
        log.info("New route: port %d -> /p/%s", port, token)
        changed = True

    active_ports = set(ports)
    stale_tokens = [
        token
        for token, info in state.items()
        if not token.startswith("__") and info.get("port") not in active_ports
    ]
    for token in stale_tokens:
        port = state[token].get("port")
        del state[token]
        log.info("Removed stale route: port %s (token %s)", port, token)
        changed = True

    if changed:
        write_map(state)
        save_state(state)
        reload_gateway()
        log.info(
            "Routes updated: %d active",
            len(state) - sum(1 for k in state if k.startswith("__")),
        )


def check_basic_auth(auth_header):
    if not ROUTER_PASSWORD:
        return True
    if not auth_header or not auth_header.lower().startswith("basic "):
        return False
    raw = auth_header.split(" ", 1)[1].strip()
    try:
        decoded = base64.b64decode(raw).decode("utf-8")
    except (ValueError, UnicodeDecodeError):
        return False
    if ":" not in decoded:
        return False
    user, pwd = decoded.split(":", 1)
    return user == ROUTER_USERNAME and pwd == ROUTER_PASSWORD


@app.post("/preview/set")
def post_preview_set():
    if not check_basic_auth(request.headers.get("Authorization")):
        return Response(
            "Unauthorized", status=401, headers={"WWW-Authenticate": "Basic"}
        )
    data = request.get_json(silent=True) or {}
    port = data.get("port")
    if port is not None:
        try:
            port = int(port)
        except (ValueError, TypeError):
            return jsonify({"error": "invalid port"}), 400
    set_preview_port(port)
    return jsonify({"ok": True, "previewPort": port})


@app.get("/preview/status")
def get_preview_status():
    if not check_basic_auth(request.headers.get("Authorization")):
        return Response(
            "Unauthorized", status=401, headers={"WWW-Authenticate": "Basic"}
        )
    return jsonify(
        {
            "previewPort": preview_port,
            "previewDomain": PREVIEW_DOMAIN or None,
        }
    )


def build_routes_payload():
    state = load_state()
    routes = []
    for token, info in sorted(state.items()):
        if token.startswith("__"):
            continue
        port = info.get("port")
        if not port:
            continue
        public_url = ""
        if PUBLIC_BASE_URL:
            public_url = f"{PUBLIC_BASE_URL}/p/{token}/"
        routes.append(
            {
                "token": token,
                "port": port,
                "publicUrl": public_url,
                "createdAt": info.get("created_at"),
            }
        )
    return {
        "routes": routes,
        "previewPort": preview_port,
        "previewDomain": PREVIEW_DOMAIN or None,
    }


@app.get("/routes")
def get_routes():
    if not check_basic_auth(request.headers.get("Authorization")):
        return Response(
            "Unauthorized", status=401, headers={"WWW-Authenticate": "Basic"}
        )

    payload = build_routes_payload()
    log.info(
        "Serving /routes (%d routes, format=%s)",
        len(payload.get("routes", [])),
        request.args.get("format", "html"),
    )

    no_cache = {
        "Cache-Control": "no-cache, no-store, must-revalidate",
        "Pragma": "no-cache",
    }

    if request.args.get("format") == "json":
        resp = jsonify(payload)
        resp.headers.update(no_cache)
        return resp

    routes_json = json.dumps(payload)
    html = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <title>Routes - OpenCode</title>
  <style>
    :root {
      --bg-0: #fafbfc; --bg-1: #f3f5f7; --bg-2: #e8ecef;
      --bg-card: #ffffff; --bg-hover: #f7f9fa;
      --text-1: #1a2332; --text-2: #4a5568; --text-3: #8694a7;
      --accent: #3b82f6; --accent-hover: #2563eb; --accent-soft: #eff6ff;
      --green: #10b981; --green-soft: #ecfdf5;
      --border: #e2e8f0; --border-focus: #93c5fd;
      --shadow: 0 1px 3px rgba(0,0,0,.06), 0 1px 2px rgba(0,0,0,.04);
      --shadow-lg: 0 4px 12px rgba(0,0,0,.08);
      --radius: 10px; --radius-lg: 14px;
      --mono: 'SF Mono', 'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace;
      --sans: -apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif;
    }
    @media (prefers-color-scheme: dark) { :root {
      --bg-0: #0f1419; --bg-1: #161b22; --bg-2: #1c2333;
      --bg-card: #1c2333; --bg-hover: #232b3a;
      --text-1: #e6edf3; --text-2: #8b949e; --text-3: #545d68;
      --accent: #58a6ff; --accent-hover: #79c0ff; --accent-soft: #161b22;
      --green: #3fb950; --green-soft: #0d1117;
      --border: #30363d; --border-focus: #388bfd;
      --shadow: 0 1px 3px rgba(0,0,0,.3); --shadow-lg: 0 4px 12px rgba(0,0,0,.4);
    }}
    html[data-theme="light"] {
      --bg-0: #fafbfc; --bg-1: #f3f5f7; --bg-2: #e8ecef;
      --bg-card: #ffffff; --bg-hover: #f7f9fa;
      --text-1: #1a2332; --text-2: #4a5568; --text-3: #8694a7;
      --accent: #3b82f6; --accent-hover: #2563eb; --accent-soft: #eff6ff;
      --green: #10b981; --green-soft: #ecfdf5;
      --border: #e2e8f0; --border-focus: #93c5fd;
      --shadow: 0 1px 3px rgba(0,0,0,.06), 0 1px 2px rgba(0,0,0,.04);
      --shadow-lg: 0 4px 12px rgba(0,0,0,.08);
    }
    html[data-theme="dark"] {
      --bg-0: #0f1419; --bg-1: #161b22; --bg-2: #1c2333;
      --bg-card: #1c2333; --bg-hover: #232b3a;
      --text-1: #e6edf3; --text-2: #8b949e; --text-3: #545d68;
      --accent: #58a6ff; --accent-hover: #79c0ff; --accent-soft: #161b22;
      --green: #3fb950; --green-soft: #0d1117;
      --border: #30363d; --border-focus: #388bfd;
      --shadow: 0 1px 3px rgba(0,0,0,.3); --shadow-lg: 0 4px 12px rgba(0,0,0,.4);
    }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: var(--sans);
      background: var(--bg-0);
      color: var(--text-1);
      min-height: 100vh;
      min-height: 100dvh;
      -webkit-font-smoothing: antialiased;
    }

    .page {
      max-width: 640px;
      margin: 0 auto;
      padding: 40px 16px 60px;
    }

    /* ---- Header ---- */
    .header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 12px;
      margin-bottom: 24px;
    }
    .header-left { flex: 1; min-width: 0; }
    .title {
      font-size: 22px;
      font-weight: 700;
      letter-spacing: -0.02em;
      line-height: 1.2;
    }
    .status {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      margin-top: 6px;
      font-size: 12px;
      color: var(--text-3);
      line-height: 1;
    }
    .status-dot {
      width: 6px; height: 6px;
      border-radius: 50%;
      background: var(--green);
      flex-shrink: 0;
    }
    .header-actions {
      display: flex;
      align-items: center;
      gap: 4px;
      flex-shrink: 0;
    }

    /* ---- Icon buttons ---- */
    .icon-btn {
      width: 34px; height: 34px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--bg-card);
      color: var(--text-2);
      cursor: pointer;
      transition: all 120ms ease;
      flex-shrink: 0;
    }
    .icon-btn:hover { background: var(--bg-hover); color: var(--text-1); border-color: var(--border-focus); }
    .icon-btn:active { transform: scale(.93); }
    .icon-btn svg { width: 16px; height: 16px; }

    /* ---- Search ---- */
    .search-wrap {
      position: relative;
      margin-bottom: 16px;
    }
    .search-icon {
      position: absolute;
      left: 11px; top: 50%; transform: translateY(-50%);
      width: 15px; height: 15px;
      color: var(--text-3);
      pointer-events: none;
    }
    .search {
      width: 100%;
      height: 38px;
      padding: 0 12px 0 34px;
      border-radius: var(--radius);
      border: 1px solid var(--border);
      background: var(--bg-card);
      color: var(--text-1);
      font-size: 13px;
      font-family: var(--sans);
      outline: none;
      transition: border-color 150ms, box-shadow 150ms;
    }
    .search::placeholder { color: var(--text-3); }
    .search:focus {
      border-color: var(--border-focus);
      box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent) 12%, transparent);
    }

    /* ---- Card list ---- */
    .list {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .card {
      background: var(--bg-card);
      border: 1px solid var(--border);
      border-radius: var(--radius-lg);
      padding: 14px 16px;
      box-shadow: var(--shadow);
      transition: box-shadow 150ms, border-color 150ms;
    }
    .card:hover {
      box-shadow: var(--shadow-lg);
      border-color: var(--border-focus);
    }
    .card-top {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .port-badge {
      display: inline-flex;
      align-items: center;
      height: 24px;
      padding: 0 8px;
      border-radius: 6px;
      background: var(--accent-soft);
      color: var(--accent);
      font-family: var(--mono);
      font-size: 12px;
      font-weight: 600;
      flex-shrink: 0;
      letter-spacing: .01em;
    }
    .card-time {
      font-size: 11px;
      color: var(--text-3);
      white-space: nowrap;
      flex-shrink: 0;
    }
    .card-url {
      display: block;
      margin-top: 8px;
      font-family: var(--mono);
      font-size: 12px;
      line-height: 1.5;
      color: var(--text-2);
      word-break: break-all;
      user-select: all;
    }
    /* ---- Empty state ---- */
    .empty {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 56px 24px;
      text-align: center;
      border: 1px dashed var(--border);
      border-radius: var(--radius-lg);
      background: var(--bg-card);
    }
    .empty-icon {
      width: 40px; height: 40px;
      color: var(--text-3);
      opacity: .5;
      margin-bottom: 16px;
    }
    .empty-title {
      font-size: 14px;
      font-weight: 600;
      color: var(--text-2);
      margin-bottom: 4px;
    }
    .empty-hint {
      font-size: 12px;
      color: var(--text-3);
      line-height: 1.5;
    }

    /* ---- Toast ---- */
    .toast {
      position: fixed;
      bottom: 24px; left: 50%; transform: translateX(-50%) translateY(80px);
      padding: 8px 16px;
      border-radius: 8px;
      background: var(--text-1);
      color: var(--bg-0);
      font-size: 12px;
      font-weight: 500;
      box-shadow: var(--shadow-lg);
      opacity: 0;
      pointer-events: none;
      transition: all 250ms cubic-bezier(.4,0,.2,1);
      z-index: 100;
    }
    .toast.show {
      opacity: 1;
      transform: translateX(-50%) translateY(0);
    }

    /* ---- Mobile ---- */
    @media (max-width: 480px) {
      .page { padding: 24px 12px 48px; }
      .title { font-size: 18px; }
      .card { padding: 12px 14px; }
      .card-time { font-size: 10px; }
      .card-url { font-size: 11px; }
    }

    /* ---- Preview badge ---- */
    .preview-bar {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 10px 14px;
      margin-bottom: 16px;
      border-radius: var(--radius);
      background: var(--accent-soft);
      border: 1px solid color-mix(in srgb, var(--accent) 20%, transparent);
      font-size: 12px;
      color: var(--text-2);
    }
    .preview-bar-icon {
      width: 14px; height: 14px;
      color: var(--accent);
      flex-shrink: 0;
    }
    .preview-bar a {
      color: var(--accent);
      text-decoration: none;
      font-family: var(--mono);
      font-weight: 500;
      word-break: break-all;
    }
    .preview-bar a:hover { text-decoration: underline; }
    .preview-bar-stop {
      margin-left: auto;
      padding: 3px 8px;
      border-radius: 5px;
      border: 1px solid var(--border);
      background: var(--bg-card);
      color: var(--text-2);
      font-size: 11px;
      cursor: pointer;
      flex-shrink: 0;
    }
    .preview-bar-stop:hover { background: var(--bg-hover); color: var(--text-1); }

    .card.previewing {
      border-color: var(--accent);
      box-shadow: 0 0 0 2px color-mix(in srgb, var(--accent) 15%, transparent);
    }
    .card-actions {
      display: flex;
      align-items: center;
      gap: 4px;
      margin-left: auto;
      flex-shrink: 0;
    }
    .card-btn {
      width: 28px; height: 28px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--border);
      border-radius: 6px;
      background: var(--bg-card);
      color: var(--text-3);
      cursor: pointer;
      transition: all 120ms ease;
    }
    .card-btn:hover { background: var(--bg-hover); color: var(--accent); border-color: var(--accent); }
    .card-btn:active { transform: scale(.9); }
    .card-btn.active { background: var(--accent-soft); color: var(--accent); border-color: var(--accent); }
    .card-btn svg { width: 14px; height: 14px; }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div class="header-left">
        <div class="title">Routes</div>
        <div class="status">
          <span class="status-dot"></span>
          <span id="count">0 active</span>
        </div>
      </div>
      <div class="header-actions">
        <button class="icon-btn" id="themeToggle" title="Toggle theme">
          <svg id="themeIcon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
          </svg>
        </button>
        <button class="icon-btn" id="copyAll" title="Copy all URLs">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
          </svg>
        </button>
        <button class="icon-btn" id="refresh" title="Refresh">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
          </svg>
        </button>
      </div>
    </div>

    <div id="previewBar"></div>

    <div class="search-wrap">
      <svg class="search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
      </svg>
      <input class="search" id="filter" placeholder="Filter by port or URL..." />
    </div>

    <section id="content"></section>
    <div class="toast" id="toast"></div>
  </div>

  <script>
    const $ = id => document.getElementById(id)
    const content = $('content'), countEl = $('count')
    const filterInput = $('filter'), toastEl = $('toast')

    // ---- Toast ----
    let toastTimer
    function toast(msg) {
      clearTimeout(toastTimer)
      toastEl.textContent = msg
      toastEl.classList.add('show')
      toastTimer = setTimeout(() => toastEl.classList.remove('show'), 1800)
    }

    // ---- Theme ----
    const sunIcon = '<circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>'
    const moonIcon = '<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>'
    const autoIcon = '<circle cx="12" cy="12" r="10"/><path d="M12 2a10 10 0 0 1 0 20z" fill="currentColor"/>'

    function applyTheme(t) {
      if (!t || t === 'auto') document.documentElement.removeAttribute('data-theme')
      else document.documentElement.setAttribute('data-theme', t)
      const icon = t === 'dark' ? moonIcon : t === 'light' ? sunIcon : autoIcon
      $('themeIcon').innerHTML = icon
      $('themeToggle').title = 'Theme: ' + (t || 'auto')
    }
    function cycleTheme() {
      const m = { light: 'dark', dark: 'auto', auto: 'light' }
      const cur = localStorage.getItem('routes-theme') || 'auto'
      const next = m[cur] || 'light'
      localStorage.setItem('routes-theme', next)
      applyTheme(next)
    }
    applyTheme(localStorage.getItem('routes-theme') || 'auto')
    $('themeToggle').addEventListener('click', cycleTheme)

    // ---- Helpers ----
    function ago(ts) {
      if (!ts) return ''
      const s = Math.floor(Date.now() / 1000 - ts)
      if (s < 60) return 'just now'
      if (s < 3600) return Math.floor(s / 60) + 'm ago'
      if (s < 86400) return Math.floor(s / 3600) + 'h ago'
      return Math.floor(s / 86400) + 'd ago'
    }
    function getUrl(r) {
      return r.publicUrl || (location.origin + '/p/' + r.token + '/')
    }

    // ---- Render ----
    function render(routes) {
      countEl.textContent = routes.length + ' active'

      if (!routes.length) {
        content.innerHTML = `
          <div class="empty">
            <svg class="empty-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
              <rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/>
            </svg>
            <div class="empty-title">No active routes</div>
            <div class="empty-hint">Start a dev server in the backend container<br/>and it will appear here automatically</div>
          </div>`
        return
      }

      const cards = routes.map(r => {
        const url = getUrl(r)
        const isPreviewing = currentData.previewPort === r.port
        const previewCls = isPreviewing ? ' previewing' : ''
        const btnCls = isPreviewing ? ' active' : ''
        return `<div class="card${previewCls}" data-url="${url}" data-port="${r.port}">
          <div class="card-top">
            <span class="port-badge">${r.port}</span>
            <span class="card-time">${ago(r.createdAt)}</span>
            <div class="card-actions">
              <button class="card-btn preview-btn${btnCls}" data-port="${r.port}" title="${isPreviewing ? 'Stop preview' : 'Preview this port'}">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>
                </svg>
              </button>
              <button class="card-btn copy-btn" data-url="${url}" title="Copy URL">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
                </svg>
              </button>
            </div>
          </div>
          <code class="card-url">${url}</code>
        </div>`
      })

      content.innerHTML = '<div class="list">' + cards.join('') + '</div>'

      content.querySelectorAll('.copy-btn').forEach(btn => {
        btn.addEventListener('click', async (e) => {
          e.stopPropagation()
          try {
            await navigator.clipboard.writeText(btn.dataset.url)
            toast('Copied')
          } catch(e) {}
        })
      })

      content.querySelectorAll('.preview-btn').forEach(btn => {
        btn.addEventListener('click', async (e) => {
          e.stopPropagation()
          const port = parseInt(btn.dataset.port)
          const isActive = currentData.previewPort === port
          await setPreview(isActive ? null : port)
        })
      })
    }

    // ---- Data ----
    let currentData = __INITIAL_DATA__

    // ---- Preview ----
    const previewBarEl = $('previewBar')
    const eyeOpenIcon = '<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>'

    function renderPreviewBar() {
      const port = currentData.previewPort
      const domain = currentData.previewDomain
      if (!port) {
        previewBarEl.innerHTML = ''
        return
      }
      const link = domain ? `<a href="https://${domain}" target="_blank">${domain}</a>` : `port ${port}`
      previewBarEl.innerHTML = `
        <div class="preview-bar">
          <svg class="preview-bar-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${eyeOpenIcon}</svg>
          <span>Preview active: ${link} &rarr; :${port}</span>
          <button class="preview-bar-stop" id="stopPreview">Stop</button>
        </div>`
      $('stopPreview').addEventListener('click', () => setPreview(null))
    }

    async function setPreview(port) {
      try {
        const res = await fetch('/preview/set', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'same-origin',
          body: JSON.stringify({ port })
        })
        if (!res.ok) { toast('Failed: ' + res.status); return }
        currentData.previewPort = port
        toast(port ? 'Preview: port ' + port : 'Preview stopped')
        renderPreviewBar()
        applyFilter()
      } catch(e) {
        toast('Error setting preview')
      }
    }

    function applyFilter() {
      const q = filterInput.value.trim().toLowerCase()
      const routes = (currentData.routes || []).filter(r =>
        !q || r.token.toLowerCase().includes(q) || String(r.port).includes(q) || getUrl(r).toLowerCase().includes(q)
      )
      render(routes)
    }

    async function load() {
      try {
        const res = await fetch('/routes?format=json', { cache: 'no-store', credentials: 'same-origin' })
        if (!res.ok) { countEl.textContent = 'error ' + res.status; return }
        currentData = await res.json()
        applyFilter()
        renderPreviewBar()
      } catch (e) {
        countEl.textContent = 'offline'
      }
    }

    $('refresh').addEventListener('click', () => { load(); toast('Refreshing...') })
    filterInput.addEventListener('input', applyFilter)
    $('copyAll').addEventListener('click', async () => {
      const urls = (currentData.routes || []).map(getUrl).join('\\n')
      if (urls) {
        await navigator.clipboard.writeText(urls)
        toast('All URLs copied')
      }
    })

    applyFilter()
    renderPreviewBar()
    setInterval(load, 8000)
  </script>
</body>
</html>
    """
    html = html.replace("__INITIAL_DATA__", routes_json)
    return Response(html, mimetype="text/html", headers=no_cache)


def loop():
    log.info(
        "Route scanner started (interval=%ds, target=%s, range=%s-%s)",
        SCAN_INTERVAL,
        TARGET_CONTAINER,
        PORT_RANGE[0],
        PORT_RANGE[1],
    )
    while True:
        try:
            sync_routes()
        except Exception:
            log.exception("Error in sync_routes")
        time.sleep(SCAN_INTERVAL)


if __name__ == "__main__":
    from threading import Thread

    log.info("Router starting on :7070")
    load_preview_state()
    t = Thread(target=loop, daemon=True)
    t.start()
    app.run(host="0.0.0.0", port=7070)
